Update main.ino
Harlem-Launch-Alliance/Catalyst-2 pull request #61
Opened 2022-08-28 07:34 UTC by mmayankkkb

Added timing note for clarity #58

2022-08-28 15:21 UTC, JonathanSafer requested changes
Please verify that the program compiles without errors or (additional) warnings

2022-08-28 15:21 UTC, JonathanSafer commented on main/main.ino
> +
Please remove this extra space on 187

2022-08-28 16:46 UTC, mmayankkkb commented on main/main.ino
> +
Done, please check the recent commit.

2022-08-28 17:10 UTC, JonathanSafer commented
Could you provide the output from the compiler log? You can find directions to set up your compilation [here](https://github.com/Harlem-Launch-Alliance/Catalyst-2/blob/main/GETTING_STARTED.md).

2022-08-28 17:12 UTC, JonathanSafer requested changes
Please change the title of the PR to `added comment for clarity` or something similar so that we can easily tell what this PR is about

2022-08-28 20:02 UTC, mmayankkkb commented
> Could you provide the output from the compiler log? You can find directions to set up your compilation [here](https://github.com/Harlem-Launch-Alliance/Catalyst-2/blob/main/GETTING_STARTED.md).

I tried to verify/compile it , but I got an error in Arduino IDE [grpc: error while marshaling: proto: Marshal called with nil
Compilation error: grpc: error while marshaling: proto: Marshal called with nil] . After researching i got to know that it requires an  Arduino  board to compile and i didn't own it.Project should work fine because I just add an comment.
![arduino](https://user-images.githubusercontent.com/111235029/187092295-0744e441-1692-4501-876a-2c0eabeebc28.JPG)

2022-08-28 20:09 UTC, JonathanSafer commented
This may be because you do not have teensyduino installed. Could you please download the software in the link that I sent and try compiling either in the teensyduino IDE or (preferably) in VSCode with PlatformIO installed? You do not need any hardware to compile the software

2022-08-28 21:19 UTC, mmayankkkb commented
> This may be because you do not have teensyduino installed. Could you please download the software in the link that I sent and try compiling either in the teensyduino IDE or (preferably) in VSCode with PlatformIO installed? You do not need any hardware to compile the software

oh.. yeah ..thanks for advice finally i am able to compile it.
                LOGS

Processing teensy41 (platform: teensy; board: teensy41; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/teensy/teensy41.html
PLATFORM: Teensy (4.17.0) > Teensy 4.1
HARDWARE: IMXRT1062 600MHz, 512KB RAM, 7.75MB Flash
DEBUG: Current (jlink) External (jlink)
PACKAGES:
 - framework-arduinoteensy @ 1.157.220801 (1.57)   
 - tool-teensy @ 1.157.0 (1.57)
 - toolchain-gccarmnoneeabi @ 1.50401.190816 (5.4.1)
Converting main.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 97 compatible libraries
Scanning dependencies...
Dependency Graph
|-- EWMA @ 1.0.2
|-- Adafruit BMP3XX Library @ 2.1.2
|   |-- Adafruit BusIO @ 1.13.2
|   |   |-- Wire @ 1.0
|   |   |-- SPI @ 1.0
|   |-- Wire @ 1.0
|   |-- SPI @ 1.0
|-- Adafruit GPS Library @ 1.7.0
|   |-- SPI @ 1.0
|   |-- Wire @ 1.0
|-- SD @ 2.0.0
|   |-- SdFat @ 2.1.2
|   |   |-- SPI @ 1.0
|-- Wire @ 1.0
Building in debug mode
Compiling .pio\build\teensy41\src\main.ino.cpp.o
Compiling .pio\build\teensy41\lib2f7\EWMA\Ewma.cpp.o
Compiling .pio\build\teensy41\libacf\Wire\Wire.cpp.o
Compiling .pio\build\teensy41\libacf\Wire\WireIMXRT.cpp.o
Compiling .pio\build\teensy41\libacf\Wire\WireKinetis.cpp.o
Compiling .pio\build\teensy41\libacf\Wire\utility\twi.c.o
Compiling .pio\build\teensy41\lib9a4\SPI\SPI.cpp.o
Compiling .pio\build\teensy41\lib745\Adafruit BusIO\Adafruit_BusIO_Register.cpp.o
Compiling .pio\build\teensy41\lib745\Adafruit BusIO\Adafruit_I2CDevice.cpp.o
Compiling .pio\build\teensy41\lib745\Adafruit BusIO\Adafruit_SPIDevice.cpp.o
Compiling .pio\build\teensy41\lib91c\Adafruit BMP3XX Library\Adafruit_BMP3XX.cpp.o
Compiling .pio\build\teensy41\lib91c\Adafruit BMP3XX Library\bmp3.c.o
In file included from C:/Users/mayank/Documents/Git/Catalyst-2/main/main.ino:13:0:
main\gy521_imu.h: In function 'imuReading getIMU()':
main\gy521_imu.h:16:41: warning: variable 'Tmp' set but not used [-Wunused-but-set-variable]
   int16_t AcX, AcY, AcZ, GyX, GyY, GyZ, Tmp;
                                         ^
In file included from C:/Users/mayank/Documents/Git/Catalyst-2/main/main.ino:15:0:
main\gps.h: In function 'String setupGPS()':
main\gps.h:42:23: warning: invalid conversion from 'char*' to 'char' [-fpermissive]
       c = GPS.lastNMEA(); //this gives an error but doesn't seem to be an issue
                       ^
main\gps.h:36:10: warning: variable 'c' set but not used [-Wunused-but-set-variable]        
     char c = GPS.read();
          ^
In file included from C:/Users/mayank/Documents/Git/Catalyst-2/main/main.ino:15:0:
main\gps.h: In function 'gpsReading getGPS()':
main\gps.h:85:23: warning: invalid conversion from 'char*' to 'char' [-fpermissive]
       c = GPS.lastNMEA(); //this gives an error but doesn't seem to be an issue
                       ^
main\gps.h:79:10: warning: variable 'c' set but not used [-Wunused-but-set-variable]
     char c = GPS.read();
          ^
C:/Users/mayank/Documents/Git/Catalyst-2/main/main.ino: In function 'void loop()':
C:/Users/mayank/Documents/Git/Catalyst-2/main/main.ino:59:11: warning: unused variable 'x' [-Wunused-variable]
       int x = 1 + 1;
           ^
C:/Users/mayank/Documents/Git/Catalyst-2/main/main.ino:65:11: warning: unused variable 'x' [-Wunused-variable]
       int x = 1 + 1;
           ^
Archiving .pio\build\teensy41\lib2f7\libEWMA.a
Compiling .pio\build\teensy41\lib26d\Adafruit GPS Library\Adafruit_GPS.cpp.o
Compiling .pio\build\teensy41\lib26d\Adafruit GPS Library\NMEA_build.cpp.o
Compiling .pio\build\teensy41\lib26d\Adafruit GPS Library\NMEA_data.cpp.o
Compiling .pio\build\teensy41\lib26d\Adafruit GPS Library\NMEA_parse.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatDbg.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatFile.cpp.o
Archiving .pio\build\teensy41\lib745\libAdafruit BusIO.a
Archiving .pio\build\teensy41\libacf\libWire.a
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatFilePrint.cpp.o
Archiving .pio\build\teensy41\lib9a4\libSPI.a
Indexing .pio\build\teensy41\lib2f7\libEWMA.a
Archiving .pio\build\teensy41\lib91c\libAdafruit BMP3XX Library.a
Indexing .pio\build\teensy41\lib745\libAdafruit BusIO.a
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatFileWrite.cpp.o
Indexing .pio\build\teensy41\libacf\libWire.a
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatFormatter.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatName.cpp.o
Indexing .pio\build\teensy41\lib9a4\libSPI.a
Archiving .pio\build\teensy41\lib26d\libAdafruit GPS Library.a
Indexing .pio\build\teensy41\lib91c\libAdafruit BMP3XX Library.a
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatPartition.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\ExFatVolume.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\ExFatLib\upcase.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatDbg.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatFile.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatFileLFN.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatFilePrint.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatFileSFN.cpp.o
Indexing .pio\build\teensy41\lib26d\libAdafruit GPS Library.a
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatFormatter.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatName.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatPartition.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FatLib\FatVolume.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FreeStack.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FsLib\FsFile.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FsLib\FsNew.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\FsLib\FsVolume.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\MinimumSerial.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SdCard\SdCardInfo.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SdCard\SdSpiCard.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SdCard\SdioTeensy.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiArtemis.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiChipSelect.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiDue.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiESP.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiParticle.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiSTM32.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiSTM32Core.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\SpiDriver\SdSpiTeensy3.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\FmtNumber.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\FsCache.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\FsDateTime.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\FsGetPartitionInfo.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\FsName.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\FsStructs.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\FsUtf.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\PrintBasic.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\common\upcase.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\iostream\StdioStream.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\iostream\StreamBaseClass.cpp.o
Compiling .pio\build\teensy41\lib931\SdFat\iostream\istream.cpp.o
Compiling .pio\build\teensy41\lib931\S [...]

2022-08-29 03:56 UTC, JonathanSafer requested changes
Looks good. Please change the title to something more relevant than `Update main.ino` and then I will approve your change. Also as an FYI, we've decided to limit contributions to this repository to members of the [HLA](hla.nyc) organization. We'll accept this one since you already made your changes, but after this if you'd like to continue to work on this project I recommend that you keep your changes in your fork. I will also update our README to reflect this contribution rule so that others are not confused.

2022-08-29 14:02 UTC, JonathanSafer approved these changes

2022-08-29 15:15 UTC, merged